# Generated by Django 5.0.6 on 2024-05-18 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='atelier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=30)),
                ('contact', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='couturier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('numero', models.IntegerField(default=0)),
                ('adresseatel', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='patron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('nomode', models.CharField(max_length=30)),
                ('explain', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('pub_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('content', models.TextField(blank=True)),
                ('num_views', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images')),
                ('is_published', models.BooleanField(default=False)),
                ('topic', models.CharField(choices=[], max_length=10)),
                ('pub_date', models.DateField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('publish_blogpost', 'Can publish a BlogPost')],
            },
        ),
    ]
