# Generated by Django 5.0.6 on 2024-05-22 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_patron_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='patron',
            name='topic',
            field=models.CharField(choices=[('Tendance', 'Tendance'), ('Culturel', 'Culturel'), ('Hautecouture', 'Hautecouture')], default='Tendance', max_length=50),
            preserve_default=False,
        ),
    ]
