# Generated by Django 5.0.6 on 2024-05-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_adresseatel_couturier_adresse_atelier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='couturier',
            name='topic',
            field=models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme'), ('Mixte', 'Mixte')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
