# Generated by Django 5.0.2 on 2024-03-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_event_delete_articles_delete_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agronome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('specialisation', models.TextField(blank=True)),
                ('pub_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
