# Generated by Django 5.0.6 on 2024-05-24 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_couturier_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couturier',
            name='topic',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
