# Generated by Django 5.0.2 on 2024-04-13 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_agronome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='content',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='num_views',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='title',
        ),
    ]
