# Generated by Django 5.0.2 on 2024-04-22 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_name_agronome_title_rename_name_article_title_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agronome',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'permissions': [('publish_blogpost', 'Can publish a BlogPost')]},
        ),
    ]
